title: Abhisheik Jadhav
logo: /assets/img/circled_headshot.png
social:
  linkedin: "https://www.linkedin.com/in/abhisheik-jadhav/"
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
email: abhisheikj@gmail.com
phone: (+1) (858) 247-9881 / (+91) 8850917224
