title: Abhisheik Jadhav
logo: /assets/img/circled_headshot.png
description: Contact me: abhisheikj@gmail.com, (+1) (858) 247-9881 / (+91) 8850917224

# show_downloads: true
theme: jekyll-theme-minimal
